function retval = Example9_2plot(X,Y)
%  This is the peaks function
% copyright MATLAB
retval=  3*(1-X).^2.*exp(-(X.^2) - (Y+1).^2) ...
   - 10*(X/5 - X.^3 - Y.^5).*exp(-X.^2-Y.^2) ...
   - 1/3*exp(-(X+1).^2 - Y.^2);